/* eslint-disable */
// GENERATED BY @zak/capability-compiler — DO NOT EDIT BY HAND.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  CapabilityRegistry,
  computeCapabilityDefinitionHash,
  parseCapabilityCompiledMeta,
  type CapabilityDefinition,
} from "@zak/capability-registry";

const dir = dirname(fileURLToPath(import.meta.url));
const definition = JSON.parse(
  readFileSync(join(dir, "definition.json"), "utf8")
) as CapabilityDefinition;
const expectedHash = readFileSync(join(dir, "definition.hash"), "utf8").trim();
const meta = parseCapabilityCompiledMeta(
  JSON.parse(readFileSync(join(dir, "meta.json"), "utf8"))
);
const fixture = JSON.parse(readFileSync(join(dir, "test.fixture.json"), "utf8")) as {
  input: Record<string, unknown>;
  output?: unknown;
};

describe("hai.particle.update@2.0.0", () => {
  it("definition hash matches definition.hash (compiler / host contract)", () => {
    expect(computeCapabilityDefinitionHash(definition)).toBe(expectedHash);
  });

  it("golden input validates against input_schema (registry / Ajv)", () => {
    const r = new CapabilityRegistry();
    r.registerCapability(definition);
    r.registerCapabilityMeta(definition.capability, definition.version, meta);
    const vr = r.validateInput(definition.capability, fixture.input, definition.version);
    expect(vr.valid).toBe(true);
  });
});
